# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry yapf mypy
        poetry install
    - name: Lint with yapf
      run: |
        diff=$(yapf -dr --style=./yapf.ini ./cloudia/)
        if [ -n "$diffs" ]; then
          echo "failed: yapf"
          exit 1
        fi
        echo "pass yapf"
    - name: Lint with mypy
      run: |
        mypy --ignore-missing-imports ./cloudia/
        if [ $? != 0 ]; then
            echo "failed: mypy"
            exit 1
        fi
        echo "pass mypy"
    - name: Unit Test
      run: |
        poetry run python -m unittest discover -s ./test/unit_test/
    - name: Integration Test
      run: |
        poetry run python ./test/integration_test/test_cloudia_plot.py
        if [ $? != 0 ]; then
            echo "failed: cloudia_plot"
            exit 1
        fi
        echo "pass cloudia_plot"
        poetry run python ./test/integration_test/test_cloudia_pandas_plot.py
        if [ $? != 0 ]; then
            echo "failed: cloudia_pandas_plot"
            exit 1
        fi
        echo "pass cloudia_pandas_plot"
